apiVersion: v1
kind: Service
metadata:
  name: bloom-room-postgres
  namespace: bloom-room-db
spec:
  selector:
    app: bloom-room-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
