# NOTE: this cors policy is currently dormant.
# to make it effective, you will need to wire it into the ingress manifest via an annotation
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: waittime-api
spec:
  headers:
    accessControlAllowOriginList:
      - https://michaelswebstuff.com
    accessControlAllowMethods:
      - GET
    accessControlMaxAge: 600
